version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - "3. to review"
  - "feature: dependencies"
  commit-message:
    prefix: "chore"
    include: "scope"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - "3. to review"
  - "feature: dependencies"
  commit-message:
    prefix: "chore"
    include: "scope"

# stable4.2
- package-ecosystem: npm
  target-branch: stable4.2
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  labels:
    - "3. to review"
    - "feature: dependencies"
